/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Application": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "ApplicationVPC": {
      "type": "sst.aws.Vpc"
    }
    "Cdn": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "DB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "OpenAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "S3": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UnprocessedVideosQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VideoProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}