/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "VidIDProAuthServer": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "VididProApplicationService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "VididProObjectStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VididProPostgresDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "VididProRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "VididProVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}